version: "3"
tasks:
  start:*:
    desc: Run a specific service
    dotenv:
      - .env
      - services/{{index .MATCH 0}}/.env
    vars:
      service: "{{index .MATCH 0}}"
    cmds:
      - docker compose -f services/{{.service}}/docker-compose.yml up -d

  stop:*:
    desc: Run a specific service
    dotenv:
      - .env
    vars:
      service: "{{index .MATCH 0}}"
    cmds:
      - docker compose -f services/{{.service}}/docker-compose.yml down

  restart:*:
    desc: Run a specific service
    dotenv:
      - .env
    vars:
      service: "{{index .MATCH 0}}"
    cmds:
      - docker compose -f services/{{.service}}/docker-compose.yml restart


  fmt:
    desc: Run formatter
    cmds:
      - terraform fmt -recursive terraform/
      - yamlfix services/

  apply:
    desc: Apply terraform changes
    dotenv:
      - .env
    dir: terraform/
    cmds:
      - terraform init
      - terraform apply -var-file=config/var.tfvars

  sync-env:
    desc: Sync all .env files to remote homelab server
    dotenv:
      - .env
    cmds:
      - scp services/cloudflared/.env $HOMELAB_USER@$HOMELAB_HOST:$HOMELAB_PROJECT_ROOT_DIR/services/cloudflared/.env
      - scp services/backup/.env $HOMELAB_USER@$HOMELAB_HOST:$HOMELAB_PROJECT_ROOT_DIR/services/backup/.env
      - scp services/memos/.env $HOMELAB_USER@$HOMELAB_HOST:$HOMELAB_PROJECT_ROOT_DIR/services/memos/.env
      - scp services/tandoor/.env $HOMELAB_USER@$HOMELAB_HOST:$HOMELAB_PROJECT_ROOT_DIR/services/tandoor/.env
      - scp services/vaultwarden/.env $HOMELAB_USER@$HOMELAB_HOST:$HOMELAB_PROJECT_ROOT_DIR/services/vaultwarden/.env
