services:
  recovery:
    image: rclone/rclone:latest
    container_name: homelab-recovery
    env_file:
      - .env
    environment:
      - RCLONE_CONFIG_S3_TYPE=s3
      - RCLONE_CONFIG_S3_PROVIDER=AWS
      - RCLONE_CONFIG_S3_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - RCLONE_CONFIG_S3_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RCLONE_CONFIG_S3_REGION=${AWS_REGION:-us-east-1}
    volumes:
      - type: bind
        source: /opt/homelab/data
        target: /data
    command: copy s3:${S3_BUCKET}/backups/homelab-compose /data --log-level INFO
